### ISSUE TITLE
[Milestone] Creation of the MVP

### ISSUE THREAD

**Issue by CarlosViller** [CarlosViller/flashcards#1]
Creacion de la version mas basica de la app, esta debe contar con:

## Requerimientos
- Tarjetas que puedan guardar una pregunta y una respuesta, esta tajerta deberia tener un efecto de voltearse para que se entienda la idea de que es una flashcard
- Un sistema de login para guardar tener un vinculo entre usuarios y tarjetas
- Metodos CRUD para las tarjetas
- Una pantalla principal donde van apareciendo las tarjetas y las puedes ir pasando

## Stack
React with Tailwind
ExpressJS
Postgres + prisma

## Features
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12

## Cosas que testear antes del launch

- [x] Login
- [x] Logout
- [x] Buscar por nombre, deberia ser case insensitive
- [x] conectar
- [x] desconectar
- [x] abrir caja
- [x] editar caja
- [x] cambiarle el nombre
- [x] cambiar contenido
- [x] empezar a estudiar
- [x] ver tus cajas en tu perfil
- [x] visitar otros perfiles
- [x] conectar con cajas de otra gente
